### ISSUE TITLE
你好！

### ISSUE THREAD

**Issue by yaochen1234** [bossfriday/bossfriday-nubybear#1]
看了一下代码， 但是不知道如何使用， 有联系方式吗？ 想请教一下

**Comment by bossfriday** [comment]
--依赖中间件：
1、ZK
--配置说明：
1、file-config.xml（文件服务配置），如果只是想跑起来，不要该端口，存储空间存储规则等，无需修改；
2、service-config.xml（服务配置），如果只是想跑起来，修改zkAddress与你所依赖的zk一致即可；
--启动：
1、run FileServerBootstrap（里面有一个main方法）
2、使用FileUploadTest中的测试代码上传文件（应答下载地址为相对路径，例如：/resource/v1/3wqd6rCzGrRzN3kq22fiVhH9MRQidss378QyfEKez81YtrrENah9X8ANBEv3）
3、手工构造完整路径，直接浏览器下载即可，例如：http://127.0.0.1:18086/resource/v1/3wqd6rCzGrRzN3kq22fiVhH9MRQidss378QyfEKez81YtrrENah9X8ANBEv3
--备注：
下载地址规则今后可能变化（功能还没有全部是实现）；

**Comment by bossfriday** [comment]
我个人profile介绍里留有联系方式：bossfriday@foxmail.com、微信：camelials

**Comment by bossfriday** [comment]
详见：https://blog.csdn.net/camelials/article/details/124613041
